#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# check if dunst is installed and if it is, copy the config
if [ command -v dunst ]; then
  DUNSTDIR=$HOME/.config/dunst
  
  # create the config dir if nonexistant
  if [ ! -d "$DUNSTDIR" ]; then
    mkdir -p $DUNSTDIR
  fi
  
  DUNSTRCPATH="$DUNSTDIR/dunstrc"
  
  # check if the rc file exists and move it if it does
  if [ -f "$DUNSTRCPATH" ]; then
    mv "$DUNSTRCPATH" "$DUNSTRCPATH.old"
  fi
  # Copy the template file to the user config directory
  cp $SCRIPTPATH/dunstrc.tmpl $DUNSTRCPATH
  
  # kill previous session and start another in a detached shell to prevent dunst taking the shell
  bash -c "killall dunst && dunst"
fi

# Install rofi theme if rofi exists on the system
if [ command -v rofi ]; then
  ROFIDIR=$HOME/.config/rofi
  
  if [ ! -d "$ROFIDIR" ]; then
    mkdir -p $ROFIDIR
  fi
  
  ROFITHEMEPATH="$ROFIDIR/themes"
  
  if [ ! -d "$ROFITHEMEPATH" ]; then
    mkdir -p $ROFITHEMEPATH
  fi
  
  
  cp "$SCRIPTPATH/nord.rasi" $ROFITHEMEPATH
  
  # preserve the old rofi config if there is one
  if [ -f "$ROFIDIR/config.rasi" ]; then
    mv "$ROFIDIR/config.rasi" "$ROFIDIR/config.rasi.old" 
  fi
  
  echo "@theme $HOME/.config/rofi/themes/nord.rasi" > "$ROFIDIR/config.rasi"
  
fi

#change your keyboard if you need it - azerty or qwerty
#setxkbmap -layout be
keybLayout=$(setxkbmap -v | awk -F "+" '/symbols/ {print $2}')

if [ $keybLayout = "be" ]; then
  cp ~/.config/leftwm/config-azerty.toml ~/.config/leftwm/config.toml
else
  cp ~/.config/leftwm/config-qwerty.toml ~/.config/leftwm/config.toml
fi

# keybindings daemon
# put your personal keybinds inside your theme and use those
if [ -f "$SCRIPTPATH/sxhkd/sxhkdrc" ] ; then
  # check if there is a keybinds-folder inside your personal theme and use it
  # to use the standard keybinds, delete the dir sxhkd inside your theme
  sxhkd -c ~/.config/leftwm/themes/current/sxhkd/sxhkdrc &
else
  # standard keybinds
  sxhkd -c ~/.config/leftwm/sxhkd/sxhkdrc &
fi

# diversity of apps to start
nm-applet &
pamac-tray &
xfce4-power-manager &
numlockx on &
blueberry-tray &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
volumeicon &
run xfce4-clipman
#conky -c ~/.config/leftwm/system-overview &
#nitrogen --restore &
#caffeine &
#vivaldi-stable &
#firefox &
#thunar &
#dropbox &
#insync start &
#discord &
#spotify &
#atom &

#boot compton or picom if it exists
if [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
elif [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

#set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-fill "$SCRIPTPATH"/nord-wallpaper.jpg
fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#boot polybar based on the number of monitors found
if [ -x "$(command -v polybar)" ]; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar -c "$SCRIPTPATH/polybar.config" mainbar &> /dev/null &
  done <<< "$monitors"
  exit 0
fi
